---
version: "3.4"

services:
  proxy:
    image: "${NGINX_IMAGE:-registry:5000/nginx:latest}"
    networks:
      - app
    ports:
      - "8080:80"
    deploy:
      placement:
        constraints:
          - node.role==worker
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

  whoami:
    image: emilevauge/whoami:latest
    networks:
      - app
    deploy:
      placement:
        constraints:
          - node.role==worker
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  app:
    driver: overlay
